baseURL = "https://shokoanime.com/"
#baseURL = "https://shokoanime.com/devsite/"
DefaultContentLanguage = "en"
paginate =  6
title = "Shoko"


[outputs]
	home = ["HTML", "RSS", "JSON"]

[taxonomies]
	category = "category"
	tag = "tag"

[languages]
	[languages.en]
		contentDir = "content/en"
		title = "Shoko"
		languageName = "English"
		weight = 1
	[languages.de]
		contentDir = "content/de"
		title = "Shoko"
		languageName = "German"
		weight = 2
	[languages.fr]
        contentDir = "content/fr"
        title = "Shoko"
        languageName = "French"
        weight = 3

