baseURL = "https://shokoanime.com/"
paginate =  6
languageCode = "en-us"
title = "Shoko Anime"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "category"
  tag = "tag"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tag"
  weight = 100
[[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2006"